### ISSUE TITLE
Small updates to 3D surface plot with time slider

### ISSUE THREAD

**Issue by rickecon** [OpenSourceMacro/OGvisualizations#13]
@hayleefay. I think we can be done with the 3D surface plot after making the following two changes.

1. Get the vertical axis label in the 3D surface upper-div plot to be vertically oriented.
2. Make the lower-div plot's buttons vertically oriented instead of horizontally oriented so they take up less space.

**Comment by hayleefay** [comment]
@rickecon Sadly, I don't think I can accomplish num 1. Vis.js doesn't seem to have that option that and, since it is a 3D plot and has to move dynamically, there is no easy way to accomplish it.

I am working on num 2 and issue #14 right now.

**Comment by rickecon** [comment]
@DoraSzasz , do you know how to make a javascript 3D image have a vertically oriented axis label on the vertical axis (item 1 above)?

I think I do. Do you want me to try it?

**Comment by rickecon** [comment]
@hayleefay cleaned this up as much as possible with PR #14 .
