### ISSUE TITLE
3D surface plot and slider bar

### ISSUE THREAD

**Issue by rickecon** [OpenSourceMacro/OGvisualizations#5]
@hayleefay . You are in charge of this visualization. We want to use Bokeh and the `surf3Dtime` directory to make a 3D surface plot of one of the household distributions (`c_{j,s,t}`, `n_{j,s,t}`, `b_{j,s+1,t+1}`) with a line plot of one of the aggregate time paths (`r_t`, `w_t`, `K_t`, `L_t`, `Y_t`, `C_t`)  and a slider bar for the time period. See the pencil drawing example below.
![surf3dtime](https://user-images.githubusercontent.com/4317690/27723982-4377b29e-5d35-11e7-94d6-5a428a3b0f3e.png)
We want:
1. The top 3D plot to be manipulable in terms of the view (perspective) and zoom.
2. Buttons on the side that allow the 3D plot to be changed among `c_{j,s,t}`, `n_{j,s,t}`, and `b_{j,s+1,t+1}`.
3. Buttons on the side that allow the aggregate time path to be changed among `r_t`, `w_t`, `K_t`, `L_t`, `Y_t`, and `C_t`.
4. A slider bar for time period that changes the highlighted point in the lower-pane aggregate time path plot and the distribution in the upper 3D plot.

@DoraSzasz has said she is happy to help you at any stage with this visualization.

**Comment by hayleefay** [comment]
@rickecon Sounds great! Would you also like the 2D version of the surface included in this?

**Comment by rickecon** [comment]
@hayleefay . PR #11 looks great. The only remaining difficulties that I see are with the top 3D plot. The vertical scale and the axis do not adjust when you change among B, C, and N. Also, let's see if we can label the buttons for the top 3D plot `b(j,s,t)`, `c(j,s,t)`, and `n(j,s,t)`.

After that, I think it would be nice to see how a 2D version of the top plot looks.

**Comment by rickecon** [comment]
This issue is essentially done with PR #12.
